name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    tags:
      - 'v[0-9]*'
    branches:
      - main
      - 'v[0-9]*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run format && git diff-files
      - run: npm run test
      - run: npm run package
      - name: Verify that `dist/index.js` is up to date
        shell: bash
        run: |
          # `ncc` produces output with mixed line endings
          test -z "$(git diff -aw HEAD -- ':(exclude)dist/index.js.map' | tee diff.txt)" || {
            echo 'Files changed after `npm run package`'
            cat diff.txt
            exit 1
          }
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: diff.txt
          path: diff.txt
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run this Action in-place
        uses: ./
        with:
          repository: git/git
          definitionId: 10
          artifact: sparse-20.04
      - name: Verify that the package was downloaded
        shell: bash
        run: test -f sparse-20.04/sparse_*.deb
  test-strip-prefix: # make sure the action works on a clean machine without building
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: microsoft/vcpkg
          path: compat/vcbuild/vcpkg
          clean: false
      - name: Run this Action in-place
        uses: ./
        with:
          repository: git/git
          definitionId: 9
          path: compat/vcbuild/vcpkg
          stripPrefix: compat/vcbuild/vcpkg/
      - name: Verify that the artifact files were downloaded
        shell: bash
        run: compat/vcbuild/vcpkg/vcpkg.exe version && ls -la compat/vcbuild/vcpkg/.git
