name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    tags:
      - 'v[0-9]*'
    branches:
      - main
      - 'v[0-9]*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run package
      - name: Verify that `dist/index.js` is up to date
        shell: bash
        run: |
          # `ncc` produces output with mixed line endings
          test -z "$(git diff -w HEAD | tee diff.txt)" || {
            echo 'Files changed after `npm run package`'
            cat diff.txt
            exit 1
          }
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run this Action in-place
        uses: ./
        with:
          repository: git/git
          definitionId: 10
      - name: Verify that the package was downloaded
        shell: bash
        run: test -f sparse_*.deb
